{% extends 'base/public/base.phtml' %}

{% block title %}首页{% endblock %}

{% block head %}
<link rel="stylesheet" href="/css/wt.css">
{% endblock %}

{% block content %}
    {% include "base/public/header.phtml" %}
	<div class="divide"><a href="#" class="bbg">栏目</a></div>
    <ul class="container">
    	<li class="list3 card">
    		<h3 class="title">标题</h3>
    		<div class="content">内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容</div>
    	</li><li class="list3line"></li><li class="list3 card">
    		<h3 class="title">标题</h3>
			<div class="content">内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容</div>
    	</li><li class="list3line"></li><li class="list3 card">
			<h3 class="title">标题</h3>
			<div class="content">内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容</div>
    	</li>
    </ul>
    <div class="divide"><a href="#" class="bbg">栏目</a></div>
    <ul class="container">
    	<li class="list4 card">
    		<h3 class="title">标题</h3>
    		<div class="content">内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容</div>
    	</li><li class="list4line"></li><li class="list4 card">
    		<h3 class="title">标题</h3>
			<div class="content">内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容</div>
    	</li><li class="list4line"></li><li class="list4 card">
			<h3 class="title">标题</h3>
			<div class="content">内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容</div>
    	</li><li class="list4line"></li><li class="list4 card">
			<h3 class="title">标题</h3>
			<div class="content">内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容</div>
    	</li>
    </ul>
    <ul class="container centernav">
    	<li>关于我们</li>
    	<li>使用帮助</li>
    	<li>意见见解</li>
    	<li>合作共赢</li>
    </ul>
    <div class="popup" style="display: none;">
    	<div class="bg"></div>
    	<div class="cbox">
    		<div class="close">&times;</div>
    		{# include "base/public/loginbox.phtml" #}
    	</div>
    </div>
{% endblock %}