<!DOCTYPE html>
<html lang="zh">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>{% block title %}{% endblock %}-A6VI</title>
    <link rel='stylesheet' href='css/pub.css' />
    <link rel="icon" href="/favicon.ico" type="image/x-icon" />
	{% block head %}
    {% endblock %}
</head>
<body>
{% block content %}{% endblock %}
<script type="text/javascript" src="js/pub.js"></script>
{% block footer %}
{% endblock %}
</body>
</html>