<div class="container">
<footer class="pt-4 my-md-5 pt-md-5">
  <div class="row">
    <div class="col-12 col-md">
      <img class="mb-2" src="/images/logo.png" alt="" width="24" height="24">
      <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
    </div>
    <div class="col-6 col-md">
      <h5>功能软件</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">促销活动</a></li>
        <li><a class="text-muted" href="#">公司办公</a></li>
        <li><a class="text-muted" href="#">业务合作</a></li>
        <li><a class="text-muted" href="#">统计分析</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>文档中心</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">新闻中心</a></li>
        <li><a class="text-muted" href="#">帮助文档</a></li>
        <li><a class="text-muted" href="#">视频指导</a></li>
        <li><a class="text-muted" href="#">免责声明</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>关于我们</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">团队展示</a></li>
        <li><a class="text-muted" href="#">联系方式</a></li>
        <li><a class="text-muted" href="#">意见建议</a></li>
        <li><a class="text-muted" href="#">历史风云</a></li>
      </ul>
    </div>
  </div>
</footer>
</div>