<nav class="navbar fixed-bottom navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">A6VI</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="A6VI">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbars">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">首页</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">企业展示</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">功能软件</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">新闻资讯</a>
        </li>
      </ul>
      <ul class="navbar-nav my-2 my-md-0">
        <li class="nav-item">
          <a class="btn btn-outline-primary" href="{{url('/gallery')}}">登陆</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-outline-primary" href="/gallery/regin">注册</a>
        </li>
      </ul>
    </div>
  </div>
</nav>