<div class="modal-dialog" style="border: 0px;">
  <div class="modal-content">
    <div class="modal-header text-center">登录</div>
    <form class="modal-body" action="" method="POST">
      <div class="form-group">
        <input type="text" name="username" class="form-control" placeholder="账号/邮箱/手机">
      </div>
      <div class="form-group">
        <input type="password" name="passwd" class="form-control" placeholder="密码">
      </div>
      <div class="checkbox">
        <label>
          <input type="checkbox" name="remember" value="1"> 记住密码
        </label>
      </div>
      <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>' value='<?php echo $this->security->getToken() ?>'/>
      <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
    </form>
  </div>
</div>