<div class="modal-dialog">
  <div class="modal-content" style="border: 0px;">
    <div class="modal-header text-center">登录</div>
    <form class="modal-body" id="login" action="" method="POST">
      <div class="form-group">
        <input type="text" name="username" v-model="username" v-bind:class="{ is-invalid: isActive}" class="form-control" placeholder="账号/邮箱/手机" value="">
      </div>
      <div class="form-group">
        <input type="password" name="passwd" v-model="passwd" class="form-control" placeholder="密码">
      </div>
      <div class="checkbox">
        <label>
          <input type="checkbox" name="remember" value="1"> 记住密码
        </label>
      </div>
      <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>' value='<?php echo $this->security->getToken() ?>'/>
      <button class="btn btn-lg btn-primary btn-block" type="button">登录</button>
    </form>
  </div>
</div>